# Generated by Django 4.0.4 on 2022-09-19 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Pelagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Cavalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço')),
                ('data_nascimento', models.DateTimeField(verbose_name='Data de nascimento')),
                ('descricao', models.CharField(max_length=255, verbose_name='Nome')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.genero', verbose_name='Genero')),
                ('habilidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.habilidade', verbose_name='Habilidade')),
                ('pelagem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.pelagem', verbose_name='Pelagem')),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.raca', verbose_name='Raça')),
            ],
        ),
    ]
