# Generated by Django 4.0.4 on 2022-09-23 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_genero_habilidade_pelagem_cavalo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cavalo',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('cavalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.cavalo')),
            ],
        ),
    ]
