# Generated by Django 4.0.4 on 2022-09-23 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_alter_cavalo_descricao_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagem',
            old_name='image',
            new_name='imagem',
        ),
    ]
