# Generated by Django 4.0.4 on 2022-09-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_alter_imagem_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cavalo',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
