# Generated by Django 4.0.4 on 2022-09-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_cavalo_aprovado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cavalo',
            name='aprovado',
        ),
        migrations.AddField(
            model_name='cavalo',
            name='status',
            field=models.CharField(default='EM ANÁLISE', max_length=20, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
