# Generated by Django 4.0.4 on 2022-09-30 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_remove_cavalo_aprovado_cavalo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cavalo',
            name='cidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cadastros.cidade', verbose_name='Cidade'),
            preserve_default=False,
        ),
    ]
