# Generated by Django 4.0.4 on 2022-10-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_cavalo_proprietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cavalo',
            name='registro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Registro'),
        ),
    ]
